class User {
    constructor(user, pfp) {
      this.username = user
      this.pfp = pfp
    }
  }
  

  
 
  
    const users = {
      'OceanDark': new User('OceanDark', 'images/pfps/OceanDark.jpg'),
      'omnivorous65': new User('omnivorous65', 'images/pfps/omnivorous65.jpg'),
      'tuig97jai': new User('tuig97jai', '/images/pfps/tuig97jai.jpg'),
      'aces9385': new User('aces9385', '/images/pfps/aces9385.jpg'),
      'baby bok choy': new User('baby bok choy', '/images/pfps/baby bok choy.jpg'),
      'Rare!': new User('Rare!', '/images/pfps/Rare!.jpg'),
      'codeFoto': new User('codeFoto', '/images/pfps/codeFoto.jpg'),
      'Mr Green thumb': new User('Mr Green thumb', '/images/pfps/Mr Green thumb.jpg'),
      'kbnped': new User('kbnped', '/images/pfps/kbnped.jpg'),
      'culota': new User('culota', '/images/pfps/culota.jpg'),
      'laurydel': new User('laurydel', '/images/pfps/laurydel.jpg'),
      'ThreeThreeThree': new User('ThreeThreeThree', '/images/pfps/ThreeThreeThree.jpg'),
      'bozoFrancois': new User('bozoFrancois', '/images/pfps/bozoFrancois.jpg'),
      'butchbutchress4': new User('butchbutchress4', '/images/pfps/butchbutchress4.jpg'),
      'Chancellor': new User('Chancellor', '/images/pfps/Chancellor.jpg'),
      'mieter most': new User('mieter most', '/images/pfps/mieter most.jpg'),
      'Allana8Bit': new User('Allana8Bit', '/images/pfps/Allana8Bit.jpg'),
      'CouchTomato33': new User('CouchTomato33', '/images/pfps/CouchTomato33.jpg'),
      'chance.': new User('chance.', '/images/pfps/chance..jpg'),
      'video1pfp': new User('video1pfp', '/images/pfps/video1pfp.jpg'),
      'dreaming blue': new User('dreaming blue', '/images/pfps/dreaming blue.jpg'),
      'Crypi Dawg': new User('Crypi Dawg', '/images/pfps/Crypi Dawg.jpg'),
      'ScissorFeet': new User('ScissorFeet', '/images/pfps/ScissorFeet.jpg'),
      'Uptown Ursula': new User('Uptown Ursula', '/images/pfps/Uptown Ursula.jpg'),
      'girl gamers 4 phoebe': new User('girl gamers 4 phoebe', '/images/pfps/girl gamers 4 phoebe.jpg'),
      'CoraPng': new User('CoraPng', '/images/pfps/CoraPng.jpg'),
      'pikkinoppi': new User('pikkinoppi', '/images/pfps/pikkinoppi.jpg'),
      'KTCTunes': new User('KTCTunes', '/images/pfps/KTCTunes.jpg'),
      'quinnalaGaming': new User('quinnalaGaming', '/images/pfps/quinnalaGaming.jpg'),
      'acacia world': new User('acacia world', '/images/pfps/acacia world.jpg'),
      'sohopowell': new User('sohopowell', '/images/pfps/sohopowell.jpg'),
      'madokamagica s2 now': new User('madokamagica s2 now', '/images/pfps/madokamagica s2 now.jpg'),
      'MoonDog': new User('MoonDog', '/images/pfps/MoonDog.jpg'),
      'illama': new User('illama', '/images/pfps/illama.jpg'),
      'NANA': new User('NANA', '/images/pfps/NANA.jpg'),
      'Несколько': new User('Несколько', '/images/pfps/Несколько.jpg'),
      'woMac': new User('woMac', '/images/pfps/woMac.jpg'),
      'coffee83920': new User('coffee83920', '/images/pfps/coffee83920.jpg'),
      'beppa big': new User('beppa big', '/images/pfps/beppa big.jpg'),
      'West of Neptune': new User('West of Neptune', '/images/pfps/West of Neptune.jpg'),
      'cweasyceasey': new User('cweasyceasey', '/images/pfps/cweasyceasey.jpg'),
      'sphere': new User('sphere', '/images/pfps/sphere.jpg'),
      'the binarian': new User('the binarian', '/images/pfps/the binarian.jpg'),
      'cookieflava': new User('cookieflava', '/images/pfps/cookieflava.jpg'),
      'GreenY': new User('GreenY', '/images/pfps/GreenY.jpg'),
      'dgunit01': new User('dgunit01', '/images/pfps/dgunit01.jpg'),
      'BlueDanny': new User('BlueDanny', '/images/pfps/BlueDanny.jpg'),
      'TheSultanMusic': new User('TheSultanMusic', '/images/pfps/TheSultanMusic.jpg'),
      'family vibes': new User('family vibes', '/images/pfps/family vibes.jpg'),
      'lexaProWinner': new User('lexaProWinner', '/images/pfps/lexaProWinner.jpg'),
      'jLu': new User('jLu', '/images/pfps/jLu.jpg'),
      'J C': new User('J C', '/images/pfps/J C.jpg'),
      'nika': new User('nika', '/images/pfps/nika.jpg'),
      'lethargy': new User('lethargy', '/images/pfps/lethargy.jpg'),
      'yonkers': new User('yonkers', '/images/pfps/yonkers.jpg'),
      'mrsmal52': new User('mrsmal52', '/images/pfps/mrsmal52.jpg'),
      'QuinYan Animation': new User('QuinYan Animation', '/images/pfps/QuinYan Animation.jpg'),
      'SweetJumperr': new User('SweetJumperr', '/images/pfps/SweetJumperr.jpg'),
      'juulRenaissance': new User('juulRenaissance', '/images/pfps/juulRenaissance.jpg'),
      'Ev': new User('Ev', '/images/pfps/Ev.jpg'),
      'icillian': new User('icillian', '/images/pfps/icillian.jpg'),
      'melful lovingpsl': new User('melful lovingpsl', '/images/pfps/melful lovingpsl.jpg'),
      'sponge_waka': new User('sponge_waka', '/images/pfps/sponge_waka.jpg'),
      'Teh Ch0sen': new User('Teh Ch0sen', '/images/pfps/Teh Ch0sen.jpg'),
      'NacHo Music': new User('NacHo Music', '/images/pfps/NacHo Music.jpg'),
      'kbone maridinga': new User('kbone maridinga', '/images/pfps/kbone maridinga.jpg'),
      'm3t4lh34ad': new User('m3t4lh34ad', '/images/pfps/m3t4lh34ad.jpg'),
      'GouseHost': new User('GouseHost', '/images/pfps/GouseHost.jpg'),
      'poca': new User('poca', '/images/pfps/poca.jpg'),
      'ohno its a ghost': new User('ohno its a ghost', '/images/pfps/ohno its a ghost.jpg'),
      'fergavicious': new User('fergavicious', '/images/pfps/fergavicious.jpg'),
      'Bin archit Omar': new User('Bin archit Omar', '/images/pfps/Bin archit Omar.jpg'),
      'CONSUL': new User('CONSUL', '/images/pfps/CONSUL.jpg'),
      'Bound': new User('Bound', '/images/pfps/Bound.jpg'),
      'Bo 2 4 u': new User('Bo 2 4 u', '/images/pfps/Bo 2 4 u.jpg'),
      'mustards': new User('mustards', '/images/pfps/mustards.jpg'),
      'vinvinvin': new User('vinvinvin', '/images/pfps/vinvinvin.jpg'),
      'alex2': new User('alex2', '/images/pfps/alex2.jpg'),
      'Mason Campos': new User('Mason Campos', '/images/pfps/MC1.png'),
      'Laurie Ingham': new User('Laurie Ingham', '/images/pfps/MC2.png'),
      'officialmelzz': new User('officialmelzz', '/images/pfps/officialmelzz.jpg'),
      'larmando22': new User('larmando22', '/images/pfps/larmando22.jpg'),
      
    }
  
    

  export default users;